# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'find_nearby.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import math

class Ui_MainWindow(object):
    list = [{"name": " ร้านลุงหนุ่ม1",
             "location": " ตึกหกดกหดกหดกหดหอศิล",
             "รสชาติ": "  ผัดกะเพราหมูกรอบ""\n"
                        " คะน้าหมูกรอบ ""\n",
             "set_locationX":0,
             "set_locationY":0,
             "distance":0,
             "img": "background-image: url(:/img_bg/images.png);"}, # ร้านที่ 1
            {"name": " ร้านลุงหนุ่ม2",
             "location": " ตึกหกดกหดกหดกหดหอศิล",
             "รสชาติ": "  ผัดกะเพราหมูกรอบ""\n"
                       " คะน้าหมูกรอบ ""\n",
             "set_locationX": 100,
             "set_locationY": 100,
             "distance": 0,
             "img": "background-image: url(:/img_bg/images.png);"}, # ร้านที่ 2
            {"name": " ร้านลุงหนุ่ม3",
             "location": " ตึกอาคารคณะศิล ที่มีสาวเยอะๆ",
             "รสชาติ": "  ผัดกะเพราหมูกรอบ""\n"
                       " คะน้าหมูกรอบ ""\n",
             "set_locationX":500,
             "set_locationY": 500,
             "distance": 0,
             "img": "background-image: url(:/img_bg/images.png);"}, # ร้านที่ 3
            {"name": " ร้านลุงหนุ่ม4",
             "location": " ตึกหกดกหดกหดกหดหอศิล",
             "รสชาติ": "  ผัดกะเพราหมูกรอบ""\n"
                       " คะน้าหมูกรอบ ""\n",
             "set_locationX": 600,
             "set_locationY": 600,
             "distance": 0,
             "img": "background-image: url(:/img_bg/images.png);"}, # ร้านที่ 4
            {"name": " ร้านลุงหนุ่ม5",
             "location": " ตึกหกดกหดกหดกหดหอศิล",
             "รสชาติ": "  ผัดกะเพราหมูกรอบ""\n"
                       " คะน้าหมูกรอบ ""\n",
             "set_locationX": 600,
             "set_locationY": 700,
             "distance": 0,
             "img": "background-image: url(:/img_bg/images.png);"}, # ร้านที่ 5
            {"name": " ร้านลุงหนุ่ม6",
             "location": " ตึกหกดกหดกหดกหดหอศิล",
             "รสชาติ": "  ผัดกะเพราหมูกรอบ""\n"
                       " คะน้าหมูกรอบ ""\n",
             "set_locationX": 900,
             "set_locationY": 700,
             "distance": 0,
             "img": "background-image: url(:/img_bg/images.png);"}, # ร้านที่ 6
            {"name": " ร้านลุงหนุ่ม7",
             "location": " ตึกหกดกหดกหดกหดหอศิล",
             "รสชาติ": "  ผัดกะเพราหมูกรอบ""\n"
                       " คะน้าหมูกรอบ ""\n",
             "set_locationX": 800,
             "set_locationY": 700,
             "distance": 0,
             "img": "background-image: url(:/img_bg/images.png);"}, # ร้านที่ 7
            {"name": " ร้านลุงหนุ่ม8",
             "location": " ตึกหกดกหดกหดกหดหอศิล",
             "รสชาติ": "  ผัดกะเพราหมูกรอบ""\n"
                       " คะน้าหมูกรอบ ""\n",
             "set_locationX": 800,
             "set_locationY": 700,
             "distance": 0,
             "img": "background-image: url(:/img_bg/images.png);"}, # ร้านที่ 8
            {"name": " ร้านลุงหนุ่ม9",
             "location": " ตึกหกดกหดกหดกหดหอศิล",
             "รสชาติ": "  ผัดกะเพราหมูกรอบ""\n"
                       " คะน้าหมูกรอบ ""\n",
             "set_locationX": 800,
             "set_locationY": 700,
             "distance": 0,
             "img": "background-image: url(:/img_bg/images.png);"}, # ร้านที่ 9
            {"name": "ร้านลุงหนุ่ม10",
             "location": "ตึก หอศิล",
             "รสชาติ": "อร่อย",
             "set_locationX": 100,
             "set_locationY": 500,
             "distance":0,
             "img": "background-image: url(:/img_bg/images.png);"}, # ร้านที่ 10
            {"name": "ร้านลุงหนุ่ม11",
             "location": "ตึก หอศิล",
             "รสชาติ": "อร่อย",
             "set_locationX": 100,
             "set_locationY": 300,
             "distance":0,
             "img": "background-image: url(:/img_bg/images.png);"}, # ร้านที่ 11
            # {"name": "ร้านลุงหนุ่ม",
            #  "location": "ตึก หอศิล",
            #  "รสชาติ": "อร่อย"},
            # {"name": "ร้านลุงหนุ่ม",
            #  "location": "ตึก หอศิล",
            #  "รสชาติ": "อร่อย"},
            # {"name": "ร้านลุงหนุ่ม",
            #  "location": "ตึก หอศิล",
            #  "รสชาติ": "อร่อย"},
            ]
    set_locationX = 0
    set_locationY = 0
    # set_lname = ["llname", "llocation", "llmenu",
    #              "llname2", "location2", "llmenu2"]

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 589)
        MainWindow.setStyleSheet("background-image: url(:/img_bg/IMG.gif);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(255, 182, 130);")
        self.centralwidget.setObjectName("centralwidget")


        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        # self.verticalLayout.setStyleSheet("background-image: url(:/img_bg/images.png);")


        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("color: rgb(255, 255, 255);")
        self.scrollArea.setStyleSheet("background-image: url(:/img_bg/images.png);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 474, 3024))
        self.scrollAreaWidgetContents.setTabletTracking(True)
        self.scrollAreaWidgetContents.setStyleSheet("background-image: url(:/img_bg/images.png);")
        self.scrollAreaWidgetContents.setStyleSheet("color: rgb(255, 255, 255);")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")



        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setMinimumSize(QtCore.QSize(450, 6000))
        self.frame.setStyleSheet("background-image: url(:/img_bg/IMG.gif);")
        # self.frame.setGeometry(500, 0, 0, 0)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(20, 40, 321, 21))
        self.comboBox.setStyleSheet("")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        # set_labellocation
        self.setlocation = QtWidgets.QLabel(self.frame)
        self.setlocation.setGeometry(QtCore.QRect(190, 10, 111, 16))
        self.setlocation.setObjectName("setlocation")
        # set_Button_push_Combo
        self.push_Combo = QtWidgets.QPushButton(self.frame)
        self.push_Combo.setGeometry(QtCore.QRect(350, 40, 71, 21))
        self.push_Combo.setObjectName("push_Combo")

        self.verticalLayout_2.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "N1"))
        self.comboBox.setItemText(1, _translate("MainWindow", "N2"))
        self.comboBox.setItemText(2, _translate("MainWindow", "N3"))
        self.comboBox.setItemText(3, _translate("MainWindow", "N4"))
        self.comboBox.setItemText(4, _translate("MainWindow", "N5"))
        self.comboBox.setItemText(5, _translate("MainWindow", "N6"))
        self.comboBox.setItemText(6, _translate("MainWindow", "N7"))
        self.comboBox.setItemText(7, _translate("MainWindow", "N8"))
        self.comboBox.setItemText(8, _translate("MainWindow", "N9"))
        self.comboBox.setItemText(9, _translate("MainWindow", "N10"))
        self.comboBox.setItemText(10, _translate("MainWindow", "N11"))
        self.comboBox.setItemText(11, _translate("MainWindow", "N12"))
        self.comboBox.setItemText(12, _translate("MainWindow", "N13"))
        self.comboBox.setItemText(13, _translate("MainWindow", "N14"))
        self.comboBox.setItemText(14, _translate("MainWndow", "N15"))
        self.comboBox.setItemText(15, _translate("MainWndow", "N16"))
        self.setlocation.setText(_translate("MainWindow", "    Set locatiob"))
        self.push_Combo.setText(_translate("MainWindow", "call_menu"))

        self.set_label()
        self.push_Combo.clicked.connect(self.call_Combobox)
        self.push_Combo.clicked.connect(self.Call_Distance)
        self.push_Combo.clicked.connect(self.sort)
        self.push_Combo.clicked.connect(self.call_Restaurant)
    def sort(self):
        self.list = sorted(self.list, key=lambda k: k["distance"], reverse=False)
    def Call_Distance(self):
        for item in self.list:
            distance = math.sqrt((self.set_locationX - item["set_locationX"])**2 +
                                 (self.set_locationY - item["set_locationY"])**2)
            item["distance"] = distance
        # self.call_Restaurant()
    def call_Restaurant(self):
        self.lname.setText(self.list[0]["name"])
        self.llocation.setText(self.list[0]["location"])
        self.lmenu.setText(self.list[0]["รสชาติ"])
        self.limg_restaurant.setStyleSheet(self.list[0]["img"])

        self.lname2.setText(self.list[1]["name"])
        self.llocation2.setText(self.list[1]["location"])
        self.lmenu2.setText(self.list[1]["รสชาติ"])
        self.limg_restaurant2.setStyleSheet(self.list[1]["img"])

        self.lname3.setText(self.list[2]["name"])
        self.llocation3.setText(self.list[2]["location"])
        self.lmenu3.setText(self.list[2]["รสชาติ"])
        self.limg_restaurant3.setStyleSheet(self.list[2]["img"])

        self.lname4.setText(self.list[3]["name"])
        self.llocation4.setText(self.list[3]["location"])
        self.lmenu4.setText(self.list[3]["รสชาติ"])
        self.limg_restaurant4.setStyleSheet(self.list[3]["img"])

        self.lname5.setText(self.list[4]["name"])
        self.llocation5.setText(self.list[4]["location"])
        self.lmenu5.setText(self.list[4]["รสชาติ"])
        self.limg_restaurant5.setStyleSheet(self.list[4]["img"])

        self.lname6.setText(self.list[5]["name"])
        self.llocation6.setText(self.list[5]["location"])
        self.lmenu6.setText(self.list[5]["รสชาติ"])
        self.limg_restaurant6.setStyleSheet(self.list[5]["img"])

        self.lname7.setText(self.list[6]["name"])
        self.llocation7.setText(self.list[6]["location"])
        self.lmenu7.setText(self.list[6]["รสชาติ"])
        self.limg_restaurant7.setStyleSheet(self.list[6]["img"])

        self.lname8.setText(self.list[7]["name"])
        self.llocation8.setText(self.list[7]["location"])
        self.lmenu8.setText(self.list[7]["รสชาติ"])
        self.limg_restaurant8.setStyleSheet(self.list[7]["img"])

        self.lname9.setText(self.list[8]["name"])
        self.llocation9.setText(self.list[8]["location"])
        self.lmenu9.setText(self.list[8]["รสชาติ"])
        self.limg_restaurant9.setStyleSheet(self.list[8]["img"])

        self.lname10.setText(self.list[9]["name"])
        self.llocation10.setText(self.list[9]["location"])
        self.lmenu10.setText(self.list[9]["รสชาติ"])
        self.limg_restaurant10.setStyleSheet(self.list[9]["img"])

        self.lname11.setText(self.list[10]["name"])
        self.llocation11.setText(self.list[10]["location"])
        self.lmenu11.setText(self.list[10]["รสชาติ"])
        self.limg_restaurant11.setStyleSheet(self.list[10]["img"])


    def set_label(self):

    #  ร้าน 1

        self.limg_restaurant = QtWidgets.QWidget
        self.limg_restaurant = QtWidgets.QLabel(self.frame)
        self.limg_restaurant.setGeometry(10, 100, 200, 240)
        self.limg_restaurant.setObjectName("limg_restaurant")
        # # self.limg_restaurant.setStyleSheet("background-image: url(:/img_bg/images.png)")

        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(220, 100, 210, 250))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_setdata = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_setdata.setObjectName("verticalLayout_setdata")
        self.verticalLayout_setdata.setContentsMargins(0, 0, 0, 0)

        self.lname = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lname.setMinimumSize(QtCore.QSize(50, 50))
        self.lname.setMidLineWidth(200)
        self.lname.setStyleSheet("background-image: url(:/img_bg/images.png); \n"
                                 "font: 25pt \"TH SarabunPSK\"; \n"
                                 "color: rgb(0, 0, 0);")
        self.verticalLayout_setdata.addWidget(self.lname)

        self.llocation = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.llocation.setObjectName("llocation2")
        self.llocation.setStyleSheet("background-image: url(:/img_bg/images.png); \n"
                                     "font: 20pt \"TH SarabunPSK\"; \n"
                                     "color: rgb(0, 0, 0);")
        self.verticalLayout_setdata.addWidget(self.llocation)
        self.lmenu = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lmenu.setObjectName("lmenu2")
        self.lmenu.setStyleSheet("background-image: url(:/img_bg/images.png); \n"
                                 "font: 20pt \"TH SarabunPSK\"; \n"
                                 "color: rgb(0, 0, 0);")
        self.verticalLayout_setdata.addWidget(self.lmenu)

    #  ร้าน 2

        self.limg_restaurant2 = QtWidgets.QWidget
        self.limg_restaurant2 = QtWidgets.QLabel(self.frame)
        self.limg_restaurant2.setGeometry(10, 400, 200, 240)
        self.limg_restaurant2.setObjectName("limg_restaurant2")

        self.verticalLayoutWidget2 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget2.setGeometry(QtCore.QRect(220, 400, 210, 250))
        self.verticalLayoutWidget2.setObjectName("verticalLayoutWidget2")
        self.verticalLayout_setdata2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget2)
        self.verticalLayout_setdata2.setObjectName("verticalLayout_setdata2")
        self.verticalLayout_setdata2.setContentsMargins(0, 0, 0, 0)
        self.lname2 = QtWidgets.QLabel(self.verticalLayoutWidget2)
        self.lname2.setMinimumSize(QtCore.QSize(50, 50))
        self.lname2.setMidLineWidth(200)
        self.lname2.setStyleSheet("background-image: url(:/img_bg/images.png); \n"
                                 "font: 25pt \"TH SarabunPSK\"; \n"
                                 "color: rgb(0, 0, 0);")
        self.verticalLayout_setdata2.addWidget(self.lname2)
        self.llocation2 = QtWidgets.QLabel(self.verticalLayoutWidget2)
        self.llocation2.setObjectName("llocation2")
        self.llocation2.setStyleSheet("background-image: url(:/img_bg/images.png); \n"
                                     "font: 20pt \"TH SarabunPSK\"; \n"
                                     "color: rgb(0, 0, 0);")
        self.verticalLayout_setdata2.addWidget(self.llocation2)
        self.lmenu2 = QtWidgets.QLabel(self.verticalLayoutWidget2)
        self.lmenu2.setObjectName("lmenu2")
        self.lmenu2.setStyleSheet("background-image: url(:/img_bg/images.png); \n"
                                 "font: 20pt \"TH SarabunPSK\"; \n"
                                 "color: rgb(0, 0, 0);")
        self.verticalLayout_setdata2.addWidget(self.lmenu2)

    #  ร้าน 3

        self.limg_restaurant3 = QtWidgets.QWidget
        self.limg_restaurant3 = QtWidgets.QLabel(self.frame)
        self.limg_restaurant3.setGeometry(10, 700, 200, 240)
        self.limg_restaurant3.setObjectName("limg_restaurant3")
        self.verticalLayoutWidget3 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget3.setGeometry(QtCore.QRect(220, 700, 210, 250))
        self.verticalLayoutWidget3.setObjectName("verticalLayoutWidget3")
        self.verticalLayout_setdata3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget3)
        self.verticalLayout_setdata3.setObjectName("verticalLayout_setdata3")
        self.verticalLayout_setdata3.setContentsMargins(0, 0, 0, 0)
        self.lname3 = QtWidgets.QLabel(self.verticalLayoutWidget3)
        self.lname3.setMinimumSize(QtCore.QSize(50, 50))
        self.lname3.setMidLineWidth(200)
        self.lname3.setStyleSheet("background-image: url(:/img_bg/images.png); \n"
                                  "font: 25pt \"TH SarabunPSK\"; \n"
                                  "color: rgb(0, 0, 0);")
        self.verticalLayout_setdata3.addWidget(self.lname3)
        self.llocation3 = QtWidgets.QLabel(self.verticalLayoutWidget3)
        self.llocation3.setObjectName("llocation3")
        self.llocation3.setStyleSheet("background-image: url(:/img_bg/images.png); \n"
                                      "font: 20pt \"TH SarabunPSK\"; \n"
                                      "color: rgb(0, 0, 0);")
        self.verticalLayout_setdata3.addWidget(self.llocation3)
        self.lmenu3 = QtWidgets.QLabel(self.verticalLayoutWidget2)
        self.lmenu3.setObjectName("lmenu3")
        self.lmenu3.setStyleSheet("background-image: url(:/img_bg/images.png); \n"
                                  "font: 20pt \"TH SarabunPSK\"; \n"
                                  "color: rgb(0, 0, 0);")
        self.verticalLayout_setdata3.addWidget(self.lmenu3)

    #  ร้าน 4

        self.limg_restaurant4 = QtWidgets.QWidget
        self.limg_restaurant4 = QtWidgets.QLabel(self.frame)
        self.limg_restaurant4.setGeometry(10, 1000, 200, 240)
        self.limg_restaurant4.setObjectName("limg_restaurant4")

        self.verticalLayoutWidget4 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget4.setGeometry(QtCore.QRect(220, 1000, 210, 250))
        self.verticalLayoutWidget4.setObjectName("verticalLayoutWidget4")

        self.verticalLayout_setdata4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget4)
        self.verticalLayout_setdata4.setObjectName("verticalLayout_setdata4")
        self.verticalLayout_setdata4.setContentsMargins(0, 0, 0, 0)
        self.lname4 = QtWidgets.QLabel(self.verticalLayoutWidget4)
        self.lname4.setMinimumSize(QtCore.QSize(50, 50))
        self.lname4.setMidLineWidth(200)
        self.lname4.setStyleSheet("background-image: url(:/img_bg/images.png); \n"
                                  "font: 25pt \"TH SarabunPSK\"; \n"
                                  "color: rgb(0, 0, 0);")

        self.verticalLayout_setdata4.addWidget(self.lname4)
        self.llocation4 = QtWidgets.QLabel(self.verticalLayoutWidget4)
        self.llocation4.setObjectName("llocation4")
        self.llocation4.setStyleSheet("background-image: url(:/img_bg/images.png); \n"
                                      "font: 20pt \"TH SarabunPSK\"; \n"
                                      "color: rgb(0, 0, 0);")
        self.verticalLayout_setdata4.addWidget(self.llocation4)
        self.lmenu4 = QtWidgets.QLabel(self.verticalLayoutWidget4)
        self.lmenu4.setObjectName("lmenu4")
        self.lmenu4.setStyleSheet("background-image: url(:/img_bg/images.png); \n"
                                  "font: 20pt \"TH SarabunPSK\"; \n"
                                  "color: rgb(0, 0, 0);")
        self.verticalLayout_setdata4.addWidget(self.lmenu4)

    #  ร้าน 5

        self.limg_restaurant5 = QtWidgets.QWidget
        self.limg_restaurant5 = QtWidgets.QLabel(self.frame)
        self.limg_restaurant5.setGeometry(10, 1300, 200, 240)
        self.limg_restaurant5.setObjectName("limg_restaurant5") # setlabelname_restaurant5

        self.verticalLayoutWidget5 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget5.setGeometry(QtCore.QRect(220, 1300, 210, 250))
        self.verticalLayoutWidget5.setObjectName("verticalLayoutWidget5")

        self.verticalLayout_setdata5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget5)
        self.verticalLayout_setdata5.setObjectName("verticalLayout_setdata5")
        self.verticalLayout_setdata5.setContentsMargins(0, 0, 0, 0)

        self.lname5 = QtWidgets.QLabel(self.verticalLayoutWidget5)
        self.lname5.setMinimumSize(QtCore.QSize(50, 50))
        self.lname5.setMidLineWidth(200)
        self.lname5.setStyleSheet("background-image: url(:/img_bg/images.png); \n"
                                  "font: 25pt \"TH SarabunPSK\"; \n"
                                  "color: rgb(0, 0, 0);")

        self.verticalLayout_setdata5.addWidget(self.lname5)
        self.llocation5 = QtWidgets.QLabel(self.verticalLayoutWidget5)
        self.llocation5.setObjectName("llocation5")
        self.llocation5.setStyleSheet("background-image: url(:/img_bg/images.png); \n"
                                      "font: 20pt \"TH SarabunPSK\"; \n"
                                      "color: rgb(0, 0, 0);")
        self.verticalLayout_setdata5.addWidget(self.llocation5)
        self.lmenu5 = QtWidgets.QLabel(self.verticalLayoutWidget5)
        self.lmenu5.setObjectName("lmenu5")
        self.lmenu5.setStyleSheet("background-image: url(:/img_bg/images.png); \n"
                                  "font: 20pt \"TH SarabunPSK\"; \n"
                                  "color: rgb(0, 0, 0);")
        self.verticalLayout_setdata5.addWidget(self.lmenu5)

    #  ร้าน 6

        self.limg_restaurant6 = QtWidgets.QWidget
        self.limg_restaurant6 = QtWidgets.QLabel(self.frame)
        self.limg_restaurant6.setGeometry(10, 1600, 200, 240)
        self.limg_restaurant6.setObjectName("limg_restaurant6") # setlabelname_restaurant5

        self.verticalLayoutWidget6 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget6.setGeometry(QtCore.QRect(220, 1600, 210, 250))
        self.verticalLayoutWidget6.setObjectName("verticalLayoutWidget6")

        self.verticalLayout_setdata6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget6)
        self.verticalLayout_setdata6.setObjectName("verticalLayout_setdata6")
        self.verticalLayout_setdata6.setContentsMargins(0, 0, 0, 0)

        self.lname6 = QtWidgets.QLabel(self.verticalLayoutWidget6)
        self.lname6.setMinimumSize(QtCore.QSize(50, 50))
        self.lname6.setMidLineWidth(200)
        self.lname6.setStyleSheet("background-image: url(:/img_bg/images.png); \n"
                                  "font: 25pt \"TH SarabunPSK\"; \n"
                                  "color: rgb(0, 0, 0);")

        self.verticalLayout_setdata6.addWidget(self.lname6)
        self.llocation6 = QtWidgets.QLabel(self.verticalLayoutWidget6)
        self.llocation6.setObjectName("llocation6")
        self.llocation6.setStyleSheet("background-image: url(:/img_bg/images.png); \n"
                                      "font: 20pt \"TH SarabunPSK\"; \n"
                                      "color: rgb(0, 0, 0);")
        self.verticalLayout_setdata6.addWidget(self.llocation6)
        self.lmenu6 = QtWidgets.QLabel(self.verticalLayoutWidget6)
        self.lmenu6.setObjectName("lmenu6")
        self.lmenu6.setStyleSheet("background-image: url(:/img_bg/images.png); \n"
                                  "font: 20pt \"TH SarabunPSK\"; \n"
                                  "color: rgb(0, 0, 0);")
        self.verticalLayout_setdata6.addWidget(self.lmenu6)

    #  ร้าน 7

        self.limg_restaurant7 = QtWidgets.QWidget
        self.limg_restaurant7 = QtWidgets.QLabel(self.frame)
        self.limg_restaurant7.setGeometry(10, 1900, 200, 240)
        self.limg_restaurant7.setObjectName("limg_restaurant7") # setlabelname_restaurant5

        self.verticalLayoutWidget7 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget7.setGeometry(QtCore.QRect(220, 1900, 210, 250))
        self.verticalLayoutWidget7.setObjectName("verticalLayoutWidget7")
        #
        self.verticalLayout_setdata7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget7)
        self.verticalLayout_setdata7.setObjectName("verticalLayout_setdata7")
        self.verticalLayout_setdata7.setContentsMargins(0, 0, 0, 0)
        #
        self.lname7 = QtWidgets.QLabel(self.verticalLayoutWidget7)
        self.lname7.setMinimumSize(QtCore.QSize(50, 50))
        self.lname7.setMidLineWidth(200)
        self.lname7.setStyleSheet("background-image: url(:/img_bg/images.png); \n"
                                  "font: 25pt \"TH SarabunPSK\"; \n"
                                  "color: rgb(0, 0, 0);")
        #
        self.verticalLayout_setdata7.addWidget(self.lname7)
        self.llocation7 = QtWidgets.QLabel(self.verticalLayoutWidget7)
        self.llocation7.setObjectName("llocation7")
        self.llocation7.setStyleSheet("background-image: url(:/img_bg/images.png); \n"
                                      "font: 20pt \"TH SarabunPSK\"; \n"
                                      "color: rgb(0, 0, 0);")
        self.verticalLayout_setdata7.addWidget(self.llocation7)
        self.lmenu7 = QtWidgets.QLabel(self.verticalLayoutWidget7)
        self.lmenu7.setObjectName("lmenu7")
        self.lmenu7.setStyleSheet("background-image: url(:/img_bg/images.png); \n"
                                  "font: 20pt \"TH SarabunPSK\"; \n"
                                  "color: rgb(0, 0, 0);")
        self.verticalLayout_setdata7.addWidget(self.lmenu7)

        #  ร้าน8

        self.limg_restaurant8 = QtWidgets.QWidget
        self.limg_restaurant8 = QtWidgets.QLabel(self.frame)
        self.limg_restaurant8.setGeometry(10, 2200, 200, 240)
        self.limg_restaurant8.setObjectName("limg_restaurant8")  # setlabelname_restaurant5

        self.verticalLayoutWidget8 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget8.setGeometry(QtCore.QRect(220, 2200, 210, 250))
        self.verticalLayoutWidget8.setObjectName("verticalLayoutWidget8")

        self.verticalLayout_setdata8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget8)
        self.verticalLayout_setdata8.setObjectName("verticalLayout_setdata8")
        self.verticalLayout_setdata8.setContentsMargins(0, 0, 0, 0)

        self.lname8 = QtWidgets.QLabel(self.verticalLayoutWidget8)
        self.lname8.setMinimumSize(QtCore.QSize(50, 50))
        self.lname8.setMidLineWidth(200)
        self.lname8.setStyleSheet("background-image: url(:/img_bg/images.png); \n"
                                  "font: 25pt \"TH SarabunPSK\"; \n"
                                  "color: rgb(0, 0, 0);")

        self.verticalLayout_setdata8.addWidget(self.lname8)
        self.llocation8 = QtWidgets.QLabel(self.verticalLayoutWidget8)
        self.llocation8.setObjectName("llocation8")
        self.llocation8.setStyleSheet("background-image: url(:/img_bg/images.png); \n"
                                      "font: 20pt \"TH SarabunPSK\"; \n"
                                      "color: rgb(0, 0, 0);")
        self.verticalLayout_setdata8.addWidget(self.llocation8)
        self.lmenu8 = QtWidgets.QLabel(self.verticalLayoutWidget8)
        self.lmenu8.setObjectName("lmenu8")
        self.lmenu8.setStyleSheet("background-image: url(:/img_bg/images.png); \n"
                                  "font: 20pt \"TH SarabunPSK\"; \n"
                                  "color: rgb(0, 0, 0);")
        self.verticalLayout_setdata8.addWidget(self.lmenu8)

    #  ร้าน 9

        self.limg_restaurant9 = QtWidgets.QWidget
        self.limg_restaurant9 = QtWidgets.QLabel(self.frame)
        self.limg_restaurant9.setGeometry(10, 2500, 200, 240)
        self.limg_restaurant9.setObjectName("limg_restaurant9")  # setlabelname_restaurant5

        self.verticalLayoutWidget9 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget9.setGeometry(QtCore.QRect(220, 2500, 210, 250))
        self.verticalLayoutWidget9.setObjectName("verticalLayoutWidget9")

        self.verticalLayout_setdata9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget9)
        self.verticalLayout_setdata9.setObjectName("verticalLayout_setdata9")
        self.verticalLayout_setdata9.setContentsMargins(0, 0, 0, 0)

        self.lname9 = QtWidgets.QLabel(self.verticalLayoutWidget9)
        self.lname9.setMinimumSize(QtCore.QSize(50, 50))
        self.lname9.setMidLineWidth(200)
        self.lname9.setStyleSheet("background-image: url(:/img_bg/images.png); \n"
                                  "font: 25pt \"TH SarabunPSK\"; \n"
                                  "color: rgb(0, 0, 0);")

        self.verticalLayout_setdata9.addWidget(self.lname9)
        self.llocation9 = QtWidgets.QLabel(self.verticalLayoutWidget9)
        self.llocation9.setObjectName("llocation9")
        self.llocation9.setStyleSheet("background-image: url(:/img_bg/images.png); \n"
                                      "font: 20pt \"TH SarabunPSK\"; \n"
                                      "color: rgb(0, 0, 0);")
        self.verticalLayout_setdata9.addWidget(self.llocation9)
        self.lmenu9 = QtWidgets.QLabel(self.verticalLayoutWidget9)
        self.lmenu9.setObjectName("lmenu9")
        self.lmenu9.setStyleSheet("background-image: url(:/img_bg/images.png); \n"
                                  "font: 20pt \"TH SarabunPSK\"; \n"
                                  "color: rgb(0, 0, 0);")
        self.verticalLayout_setdata9.addWidget(self.lmenu9)

    #  ร้าน 10

        self.limg_restaurant10 = QtWidgets.QWidget
        self.limg_restaurant10 = QtWidgets.QLabel(self.frame)
        self.limg_restaurant10.setGeometry(10, 2800, 200, 240)
        self.limg_restaurant10.setObjectName("limg_restaurant10")  # setlabelname_restaurant5

        self.verticalLayoutWidget10 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget10.setGeometry(QtCore.QRect(220, 2800, 210, 250))
        self.verticalLayoutWidget10.setObjectName("verticalLayoutWidget10")

        self.verticalLayout_setdata10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget10)
        self.verticalLayout_setdata10.setObjectName("verticalLayout_setdata10")
        self.verticalLayout_setdata10.setContentsMargins(0, 0, 0, 0)

        self.lname10 = QtWidgets.QLabel(self.verticalLayoutWidget10)
        self.lname10.setMinimumSize(QtCore.QSize(50, 50))
        self.lname10.setMidLineWidth(200)
        self.lname10.setStyleSheet("background-image: url(:/img_bg/images.png); \n"
                                  "font: 25pt \"TH SarabunPSK\"; \n"
                                  "color: rgb(0, 0, 0);")

        self.verticalLayout_setdata10.addWidget(self.lname10)
        self.llocation10 = QtWidgets.QLabel(self.verticalLayoutWidget10)
        self.llocation10.setObjectName("llocation10")
        self.llocation10.setStyleSheet("background-image: url(:/img_bg/images.png); \n"
                                      "font: 20pt \"TH SarabunPSK\"; \n"
                                      "color: rgb(0, 0, 0);")
        self.verticalLayout_setdata10.addWidget(self.llocation10)
        self.lmenu10 = QtWidgets.QLabel(self.verticalLayoutWidget10)
        self.lmenu10.setObjectName("lmenu10")
        self.lmenu10.setStyleSheet("background-image: url(:/img_bg/images.png); \n"
                                  "font: 20pt \"TH SarabunPSK\"; \n"
                                  "color: rgb(0, 0, 0);")
        self.verticalLayout_setdata10.addWidget(self.lmenu10)

    #  ร้าน 11

        self.limg_restaurant11 = QtWidgets.QWidget
        self.limg_restaurant11 = QtWidgets.QLabel(self.frame)
        self.limg_restaurant11.setGeometry(10, 3100, 200, 240)
        self.limg_restaurant11.setObjectName("limg_restaurant11")  # setlabelname_restaurant5

        self.verticalLayoutWidget11 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget11.setGeometry(QtCore.QRect(220, 3100, 210, 250))
        self.verticalLayoutWidget11.setObjectName("verticalLayoutWidget11")

        self.verticalLayout_setdata11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget11)
        self.verticalLayout_setdata11.setObjectName("verticalLayout_setdata11")
        self.verticalLayout_setdata11.setContentsMargins(0, 0, 0, 0)

        self.lname11 = QtWidgets.QLabel(self.verticalLayoutWidget11)
        self.lname11.setMinimumSize(QtCore.QSize(50, 50))
        self.lname11.setMidLineWidth(200)
        self.lname11.setStyleSheet("background-image: url(:/img_bg/images.png); \n"
                                   "font: 25pt \"TH SarabunPSK\"; \n"
                                   "color: rgb(0, 0, 0);")

        self.verticalLayout_setdata11.addWidget(self.lname11)
        self.llocation11 = QtWidgets.QLabel(self.verticalLayoutWidget11)
        self.llocation11.setObjectName("llocation11")
        self.llocation11.setStyleSheet("background-image: url(:/img_bg/images.png); \n"
                                       "font: 20pt \"TH SarabunPSK\"; \n"
                                       "color: rgb(0, 0, 0);")
        self.verticalLayout_setdata11.addWidget(self.llocation11)
        self.lmenu11 = QtWidgets.QLabel(self.verticalLayoutWidget11)
        self.lmenu11.setObjectName("lmenu11")
        self.lmenu11.setStyleSheet("background-image: url(:/img_bg/images.png); \n"
                                   "font: 20pt \"TH SarabunPSK\"; \n"
                                   "color: rgb(0, 0, 0);")
        self.verticalLayout_setdata11.addWidget(self.lmenu11)

    #  ร้าน 12

        self.limg_restaurant12 = QtWidgets.QWidget
        self.limg_restaurant12 = QtWidgets.QLabel(self.frame)
        self.limg_restaurant12.setGeometry(10, 3400, 200, 240)
        self.limg_restaurant12.setObjectName("limg_restaurant12")  # setlabelname_restaurant5

        self.verticalLayoutWidget12 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget12.setGeometry(QtCore.QRect(220, 3400, 210, 250))
        self.verticalLayoutWidget12.setObjectName("verticalLayoutWidget12")

        self.verticalLayout_setdata12 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget11)
        self.verticalLayout_setdata12.setObjectName("verticalLayout_setdata12")
        self.verticalLayout_setdata12.setContentsMargins(0, 0, 0, 0)

        self.lname12 = QtWidgets.QLabel(self.verticalLayoutWidget11)
        self.lname12.setMinimumSize(QtCore.QSize(50, 50))
        self.lname12.setMidLineWidth(200)
        self.lname12.setStyleSheet("background-image: url(:/img_bg/images.png); \n"
                                   "font: 25pt \"TH SarabunPSK\"; \n"
                                   "color: rgb(0, 0, 0);")

        self.verticalLayout_setdata12.addWidget(self.lname11)
        self.llocation12 = QtWidgets.QLabel(self.verticalLayoutWidget11)
        self.llocation12.setObjectName("llocation12")
        self.llocation12.setStyleSheet("background-image: url(:/img_bg/images.png); \n"
                                       "font: 20pt \"TH SarabunPSK\"; \n"
                                       "color: rgb(0, 0, 0);")
        self.verticalLayout_setdata12.addWidget(self.llocation11)
        self.lmenu12 = QtWidgets.QLabel(self.verticalLayoutWidget11)
        self.lmenu12.setObjectName("lmenu11")
        self.lmenu12.setStyleSheet("background-image: url(:/img_bg/images.png); \n"
                                   "font: 20pt \"TH SarabunPSK\"; \n"
                                   "color: rgb(0, 0, 0);")
        self.verticalLayout_setdata11.addWidget(self.lmenu11)



    def call_Combobox(self):
        print("ทำงาน")
        if self.comboBox.currentText() == "N1" :
            self.set_locationX = 0
            self.set_locationY = 0
            print("คุณอนู่ตึกn1")
        elif self.comboBox.currentText() == "N2" :
            self.set_locationX = 100
            self.set_locationY = 100
            print("คุณอนู่ตึกn2")
        elif self.comboBox.currentText() == "N3" :
            self.set_locationX = 500
            self.set_locationY = 500
            print("คุณอนู่ตึก3")
        elif self.comboBox.currentText() == "N4" :
            self.set_locationX = 1000
            self.set_locationY = 1000
        elif self.comboBox.currentText() == "N5" :
            self.set_locationX = 2000
            self.set_locationY = 2000



import img_bg_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    # call class_Ui_Mainwindow
    ui = Ui_MainWindow()

    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
