# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from find_nearby import Ui_MainWindow

class Ui_smain(object):

    def OpenWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
    def setupUi(self, smain):
        smain.setObjectName("smain")
        smain.resize(500, 500)
        smain.setMinimumSize(QtCore.QSize(500, 500))
        smain.setMaximumSize(QtCore.QSize(500, 500))
        smain.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        smain.setTabletTracking(False)
        smain.setAcceptDrops(True)
        smain.setAutoFillBackground(False)
        smain.setStyleSheet("background-image: url(:/img_bg/IMG.gif);")
        smain.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(smain)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 7, 16))
        self.label.setMaximumSize(QtCore.QSize(1000000, 1500000))
        self.label.setAcceptDrops(False)
        self.label.setStatusTip("")
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-image: url(:/newPrefix/kmutt_App/4f9c384081887aa7c5c7158094caf4f2.jpg);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/kmutt_App/unnamed.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(110, 240, 281, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setMaximumSize(QtCore.QSize(1800000, 1800000))
        self.pushButton.setObjectName("pushButton")
        # self.pushButton.clicked.connect(self.OpenWindow)
        self.pushButton.clicked.connect(self.OpenWindow)
        self.pushButton.setStyleSheet("font: 32pt \"FC Lamoon\";")

        # self.pushButton.clicked.connect(self.setupUi)

        self.horizontalLayout.addWidget(self.pushButton)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(110, 340, 281, 71))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 20, 201, 161))
        self.label_2.setStyleSheet("image: url(:/img_bg/icon_ui.jpg);")
        self.label_2.setText("")

        # self.label_2.setStyleSheet("font: 18pt \"FC Lamoon\";")
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 340, 281, 71))
        self.pushButton_2.setMaximumSize(QtCore.QSize(1800000, 1800000))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setStyleSheet("font: 32pt \"FC Lamoon\";")

        smain.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(smain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 22))
        self.menubar.setObjectName("menubar")
        smain.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(smain)
        self.statusbar.setObjectName("statusbar")
        smain.setStatusBar(self.statusbar)

        self.retranslateUi(smain)
        QtCore.QMetaObject.connectSlotsByName(smain)
    def retranslateUi(self, smain):
        _translate = QtCore.QCoreApplication.translate
        smain.setWindowTitle(_translate("smain", "หน้าเลือก location"))
        self.pushButton.setText(_translate("smain", "Find for food"))
        self.pushButton_2.setText(_translate("smain", "Random for food"))
import img_bg_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    smain = QtWidgets.QMainWindow()
    ui = Ui_smain()
    ui.setupUi(smain)
    smain.show()
    sys.exit(app.exec_())
